---
apiVersion: v1
kind: Service
metadata:
  name: policy-server
  namespace: kyverno
spec:
  selector:
    app: policy-server
  ports:
  - name: https
    port: 10250
    protocol: TCP
    targetPort: 10250
