apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: policy-server
  name: policy-server
  namespace: kyverno
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    k8s-app: metrics-server